### ISSUE TITLE
Potential improvement to shouldComponentUpdate.

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts-react#1]
Hello, I have received the following feedback from someone who has tested the wrapper, and I thought it best to post it here for consideration.
> In my experience, the difficult part of this component is to control the chart re-rendering. So the “shouldComponentUpdate" function should be smart enough to detect any change in the options property. Us “update” property to manually refresh this component is really not a good way.

I will share this issue with the user, so you may receive further comments later, should the user want to contribute more to this case.

**Comment by KacperMadej** [comment]
For now if you create a new object for chart.options then changes will be auto-detected.

Changes in a nested object, like chart's options, are not auto-detected and comparing old options with new ones might take some time. This is not a big problem unless the compare runs often, and unfortunately it does.

We could prepare a code that will make a deep compare and even use a more dedicated updates for e.g. axis or series changes. Now only chart.update is used. Next we'll need to check performance. This could be a nice enhancement for future version of the wrapper.

Let's see who else would require this feature by adding more comments in the issue thread since there's no userVoice for the wrapper.

**Comment by KacperMadej** [comment]
React does not deeply compare props by default. 
We are already using custom change detection (for the `update` flag), so we could detect what kind of change was done to decide what function should be used there.

**Comment by BrandonWilliamsCS** [comment]
You could allow `update` to be a predicate function and just defer to its return value.
e.g.,

```
  shouldComponentUpdate: function (nextProps, nextState) {
    var update = this.props.update

    // allow client update resolution
    if (typeof update === 'function') {
        return update(nextProps, nextState);
    }

    // Update if not specified or set to true
    return (typeof update === 'undefined') || update
  },
```

That would provide maximum flexibility without much extra logic to maintain.

**Comment by ppotaczek** [comment]
Actually the wrapper uses [React.PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent)’s shouldComponentUpdate to compare the options. The best way to update is to keep all chart options in the state and call `setState` with the new ones:

    constructor(props) {
      this.state = {
        chartOptions: {...},
        hoverData: null
      };
    }

    setHoverData = (e) => {
      this.setState({ hoverData: ... }); // the chart is not updated
    }

    setNewSeriesData = () => {
      this.setState({ chartOptions: {...} }); // the chart is updated with only new options
    }

    render() {
      ...
      return (
        <div>
          <HighchartsReact
            ...
            options={this.state.chartOptions}
          />
        ...
        </div>
      )
    }

Live demo: https://stackblitz.com/edit/react-9hwir4?file=index.js

Additionally, it is also possible to block updates by the `allowChartUpdate` option.
