### ISSUE TITLE
Reflow not called on first load

### ISSUE THREAD

**Issue by ngtrunghuan** [highcharts/highcharts-react#121]
Hi,

I have an issue when used with AntDesign.  Reflow not called upon first load.

The code is as simple as:
```
<Row gutter={8}>
  <Col md={16} sm={24}>
      <HighchartsReact
        highcharts={Highcharts}
        constructorType={'stockChart'}
        options={{
          series: [{
            data: [1,2,3]
          }],
          scrollbar: {
            enabled: false,
          },
          rangeSelector: {
            enabled: false,
          },
          navigator: {
            enabled: false,
          },
          chart: {
            height: '200px',
            reflow: true, //First load has issues. Reflow is not called.
          },
        }}
      />
    
  </Col>
  <Col md={8} sm={24}>
    <Table 
      columns={columns}
      dataSource={data}
      showHeader={false}
      pagination={false}
      size="small"
    />
  </Col>
</Row>
```

However, once I resize the window, reflow is called and it works as expected.

Thanks for taking a look!

**Comment by ppotaczek** [comment]
Hi @ngtrunghuan,

Thank you for reporting!

Could you reproduce that issue in some online code editor? I tried to use the code you provided but it seems to work correctly: https://codesandbox.io/s/w7mkxy4v1k

Best regards!

**Comment by fantapop** [comment]
I'm having the same issue.  For me it seems to be caused by a menu on the left pushing the chart over and the chart not knowing how big it can be created.  Here is a codesandbox:

https://codesandbox.io/s/w0jmn3kz8w

**Comment by fantapop** [comment]
I misunderstood what this question was about.  reflow: true, is actually the default.  The option is whether reflow should be called on page resize.   I'm having issues on the initial load.  I see there are other issues about that but none of the answers seem satisfactory...

**Comment by ppotaczek** [comment]
Hello,

This issue is not caused by the wrapper or by Highcharts, but by `Ant Design` module.

The chart component need to be wrapped by `Content`, and `Layout ` must have enabled `hasSider` property.

    <Layout hasSider={true}>
      <Sider>
        ...
      </Sider>
      <Content>
        <ReactHighcharts
          highcharts={Highcharts}
          options={...}
        />
      </Content>
    </Layout>,

Live demo: https://codesandbox.io/s/9zvpw0vnkw
Docs: https://ant.design/components/layout/

Best regards!

**Comment by fantapop** [comment]
Thank you for looking into this. I’ll examine the css changes when using
the hasSider flag. I’m not actually using ant components but running into
the same issue. I assume the fix will be similar.

**Comment by oferitz** [comment]
I'm not using antd either and having the same issue. my chart is inside css grid item (don't know if it matters) and never renders on the initial load. only re-render by changing the state causing the chart to appear.

First render:
![first_render](https://user-images.githubusercontent.com/1668687/57764464-2e344080-770c-11e9-8420-17534d5e3f1b.png)

re-render by changing state:
![re-render](https://user-images.githubusercontent.com/1668687/57764490-3ee4b680-770c-11e9-9a1e-942131f0885f.png)

To make it clear - there is series data in the first render.

**Comment by ppotaczek** [comment]
Hi @oferitz,

Could you reproduce the issue in some online code editor?

Best regards!

**Comment by oferitz** [comment]
@ppotaczek Thanks for the response. The issue i described doesn't really happen to me on a "real" app since the data for my charts is always coming from some API. therefore i always have a re-render after setting the state with the fetched data. 
So in my case it's not a big deal. I just wanted to let you know that this issue doesn't necessarily related to antd.

**Comment by ppotaczek** [comment]
@oferitz, Thank you for the information. To fix the issue I need to reproduce it first, so your example with a static data could be very useful.

**Comment by gregwhitworth** [comment]
I'm also hitting this issue - I've looked at numerous of the statements on how to fix this, specifically I'm using React and it works just fine if you invalidate the screen in any way. Everywhere I've looked there is a statement that says calling reflow() will work but I'm not sure how to do this in a componentize way. help providing the component (which again works outside of the invalidation issue):

```
import React from 'react'
import Highcharts from 'highcharts/highcharts'
import HighchartsReact from 'highcharts-react-official'

const options = {
  chart: {
      type: 'column'
  },
  title: {
      text: 'Browser market shares. January, 2018'
  },
  subtitle: {
      text: 'Click the columns to view versions. Source: <a href="http://statcounter.com" target="_blank">statcounter.com</a>'
  },
  xAxis: {
      type: 'category'
  },
  yAxis: {
      title: {
          text: 'Total percent market share'
      }

  },
  legend: {
      enabled: false
  },
  plotOptions: {
      series: {
          borderWidth: 0,
          dataLabels: {
              enabled: true,
              format: '{point.y:.1f}%'
          }
      }
  },
  tooltip: {
      headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
      pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
  },
  series: [
      {
          name: "Controls",
          colorByPoint: true,
          data: [
              {
                  name: "Select",
                  y: 10.73
              },
              {
                  name: "Checkbox",
                  y: 10.13
              },
              {
                  name: "Radio",
                  y: 8.34
              }
          ]
      }
  ]
}

const Top10Created = () => <HighchartsReact
  highcharts={Highcharts}
  constructorType={'chart'}
  options={options}
/>

export default Top10Created
```

Additionally, the container is using the offset as expected and has no CSS styles applied to it and is within a block container that allows it to be 100% of its parent. Most people are saying to call this on `componentDidMount()` or in `componentDidUpdate()` but since this is following one of the examples using HighChartsReact I'm not entirely sure where to place these events since we're not actually creating a React component using the normal extend and render examples. *Note: I'm pretty new to react and JSX in general, so I apologize if this is a somewhat noob question*

Thanks!

**Comment by gregwhitworth** [comment]
Ok, so I was able to prove that this is indeed the need but am doing it in a very hacky manner, but at least the user isn't having to resize the window in any manner to cause the graph to look correct:

`class Top10Created extends Component {
  componentDidMount() {
    setTimeout(() => chart.reflow(), 500);
  }

  render() {
    return <HighchartsReact
      highcharts={Highcharts}
      constructorType={'chart'}
      options={options}
      ref=''
    />
  }
}

export default Top10Created`

Any advice on how to improve that is appreciated.

**Comment by gregwhitworth** [comment]
To provide further evidence to this here is the dev tools showing the dimensions before and after:

![image](https://user-images.githubusercontent.com/865244/59994817-1bb1fe80-960a-11e9-9095-a0f52b134bd1.png)

And then here is after resizing the window

![image](https://user-images.githubusercontent.com/865244/59994889-54ea6e80-960a-11e9-99a3-7c51fa09b6e7.png)

**Comment by gregwhitworth** [comment]
Sorry to continue to add to this thread but I wanted to share one solution I came up with. Due to how React's lifecycle along with Highcharts update methods work (eg: forcing a redraw numerous times and setting it's flag of dirty to true results in no changes even calling reflow) I created a hacky workaround (ideas welcome if you come up with a better solution).

I know my main container that highcharts should be sizing itself to (in this case an `<article>`. So I setup a timeout in `componentDidMount` to poll every 10ms and store the Id for cancelling after we've fixed the issue. Then I have this method which compares the constricting container's width to the chart's clientWidth and if they aren't the same then I call `chart.reflow()`. Once they're equal I cancel the timeout. Adding a `console.log()` the `checkBounds` method was only called once on my page.

Note: I tried to use this.forceUpdate() but as I noted above, the update still fired before the layout was to the dimensions that it mattered so this was missed unfortunately. Having to a DOM call feels dirty since it creates a dependency on the DOM but I need this to work :(

Here is the code in full:

```
import React, {Component} from 'react';
import Highcharts from 'highcharts/highcharts'
import HighchartsReact from 'highcharts-react-official'

let chart = null;
let timerId = null;
const options = {
  chart: {
      type: 'column',
      events: {
        load: function () {
          chart = this;
        }
      }
  },
  title: {
      text: ''
  },
  xAxis: {
      type: 'category'
  },
  yAxis: {
      title: {
          text: 'Percentage'
      }

  },
  legend: {
      enabled: false
  },
  plotOptions: {
      series: {
          borderWidth: 0,
          dataLabels: {
              enabled: true,
              format: '{point.y:.1f}%'
          }
      }
  },
  tooltip: {
      headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
      pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
  },
  series: [
      {
          name: "Chart Name",
          colorByPoint: true,
          data: [
              {
                  name: "One",
                  y: 10.73
              },
              {
                  name: "Two",
                  y: 10.13
              },
              {
                  name: "Three",
                  y: 8.34
              }
          ]
      }
  ]
}

class Top10Created extends Component {
  componentDidMount() {
    timerId = setTimeout(() => this.checkBounds(), 10);
  }

  checkBounds() {
    let w = chart.container.clientWidth;
    let article = window.document.getElementsByTagName('article')[0];

    if (article) {
      let articleWidth = article.clientWidth;
      if (articleWidth != w) {
        chart.reflow();
        window.clearTimeout(timerId);
      }
    }
  }

  render() {
    return <HighchartsReact
      highcharts={Highcharts}
      constructorType={'chart'}
      options={options}
      ref={this.myRef}
    />
  }
}

export default Top10Created
```

**Comment by ppotaczek** [comment]
Hi @gregwhitworth,

I think that using `setTimeout` is not the best solution. You have shared the structure of your chart component, but I do not know how the parent structure looks like. Could you extend this example: https://codesandbox.io/s/highcharts-react-demo-pwvbj to demonstrate the issue?

Best regards!

**Comment by gregwhitworth** [comment]
@ppotaczek completely agree, when I get a chance I'll try to convert it over; much appreciated.

**Comment by VasimPatel** [comment]
Hello, I'm hitting this issue as well. The chart is inside a flex container and on its initial render it is smaller than the container, the height is defaulting to 400. When resizing the window in any way, it fits perfectly into the container. Any idea on what could be causing this?

**Comment by ppotaczek** [comment]
Hi @VasimPatel,

Could you reproduce the issue in some online code editor?

Best regards!

**Comment by kirankalyan5** [comment]
> Hello, I'm hitting this issue as well. The chart is inside a flex container and on its initial render it is smaller than the container, the height is defaulting to 400. When resizing the window in any way, it fits perfectly into the container. Any idea on what could be causing this?
> 
> edit: I am encountering this issue in chrome but not firefox

I have a similar issue, any workarounds?

For now , I'm setting a fixed width for the chart  via the `HighchartsReact` like this `containerProps={{ style: { width: '832'} }}`

But I would not like to pass the width as I expect the chart to be responsive.

**Comment by ppotaczek** [comment]
@kirankalyan5 - Could you provide me with some live example?
