### ISSUE TITLE
Is highcharts required?

### ISSUE THREAD

**Issue by anikolaev** [highcharts/highcharts-react#137]
Does highcharts library need to be installed separately? From Readme:
```bash
npm install highcharts-react-official
```
When I do it I get the warning: 
```
warning " > highcharts-react-official@2.2.2" has unmet peer dependency "highcharts@>=5.0.0".
```
In the old version of Readme it was:
```bash
npm install highcharts-react-official highcharts react react-dom
```

Please update the documentation if required.

**Comment by Denyllon** [comment]
@ppotaczek
Maybe we should consider to mention in documentation about the fact, that it's **required to install** `highcharts` and `react` packages in the application where using this wrapper? Current description is a bit confusing, because there is no any mention  in [General Prerequisites](https://github.com/highcharts/highcharts-react#general-prerequisites) section, that the Highcharts and React are project dependencies.

_Suggestion:_
### General prerequisites

Make sure you have **node**, and **NPM** globally installed and up to date.
Tested and required versions:

* `node` v8.11.3+,
* `npm` v6.4.1+ or similar package manager

This wrapper also requires `highcharts` and `react` packages with following versions installed in your project:

* `highcharts` v5.0.0+,
* `react` v16.4+

### Installing

Get package from NPM in your React app:

```bash
npm install highcharts-react-official
```

**Comment by anikolaev** [comment]
Maybe it is better to recommend installing it this way if Highcharts library is not installed yet:

`npm install highcharts highcharts-react-official`

It is very likely that React is already installed and Highcharts is not. 
BTW, adding line about `yarn` could be useful too.

**Comment by ppotaczek** [comment]
Hello,

Thank you for your suggestions! I have added both of the descriptions to the docs.

Best regards!
