### ISSUE TITLE
Highstock x-axis datetime not working

### ISSUE THREAD

**Issue by iherger** [highcharts/highcharts-react#147]
I am using 
```typescript
<HighchartsReact highcharts={Highcharts} constructorType={'stockChart'} options={options} />
```
with the options
```
    xAxis: {
      type: 'datetime',
      labels: {
        format: '{value:%Y-%m-%d}',
      },
      minTickInterval: 28 * 24 * 3600 * 1000,
      max: now(),
    },
```
Data points are in the form:
```
[1553592414000, 43]
[1553688739000, 44]
[1553714363000, 45]
[1553792028000, 44]
[1553805488000, 43]
[1553805488000, 42]
[1553806838000, 43]
[1553962285000, 44]
```

The x-axis of the resulting chart is, however, `linear` and not `datetime`, see screenshot below.

<img width="557" alt="Screenshot 2019-07-25 at 11 14 06" src="https://user-images.githubusercontent.com/36133712/61862559-5db2b680-aece-11e9-8983-2d3946eb36b7.png">

Is this a bug or do I need to change anything in my options and/or data series?

**Comment by ppotaczek** [comment]
Hi @iherger,

Thank you for contacting us!

Unfortunately, I do not quite understand what your problem is. Could you provide me with more detailed description of the issue - some minimal live example would be very useful? Also, you can try to disable `ordinal` option for the `xAxis` and check the result.

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-w127i

Best regards!

**Comment by iherger** [comment]
Thank you very much for your quick answer.

Disabling `ordinal` fixed it, the chart now looks as it should: 

<img width="533" alt="Screenshot 2019-07-25 at 12 02 53" src="https://user-images.githubusercontent.com/36133712/61865803-319a3400-aed4-11e9-8366-bb677a332277.png">
