### ISSUE TITLE
No animations on update

### ISSUE THREAD

**Issue by gperdomor** [highcharts/highcharts-react#15]
Hi...

I notice that when update the chart options, the update does not use animations. That should be improved :D

**Comment by KacperMadej** [comment]
Hi @gperdomor 

The updates are done through chart.update and in Highcharts version 6.1.0 the updates were improved to add more animation:

> Added feature to animate the series when updating data through `Series.setData`, `Series.update` or `Chart.update`. The new logic looks for matching X values and can be disabled through `setData's` `updatePoints` option.

[source](https://www.highcharts.com/documentation/changelog)

Any further improvements of update depends heavily on `chart.update` function animation support, so it's a Highcharts issue as long as the wrapper is based on `chart.update` function when updating.

**Comment by romaindso** [comment]
Hi,
Any update on this ?

The only dirty workaround I found is to set a random key on the Highcharts wrapper.  It force React to create a new component instance rather than update the current one. And so the initial animation is present.

```
<HighchartsReact
  highcharts={Highcharts}
  options={options}
  key={Math.random()}
/>
```

Currently, I'm not able to reproduce a dynamic solid gauge like in the official doc with the highcharts-react lib.  https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/gauge-solid/

**Comment by KacperMadej** [comment]
Hi @romaindso 

Destroy & rebuild instead of update is not optimal, but if you are interested in initial animation then it's the only way through official API.

The wrapper is limited by the Highcharts core in case of this feature - as long as this feature works the same in pure JS version of Highcharts it is not a wrapper bug.

**Comment by romaindso** [comment]
Hi @KacperMadej 

I'm interested to get an animation when data change over time like @gperdomor explained. That's why I'm doing this that way because the only animation occur during the init of the component (even if it's not optimal you right) 

On my previous link it seems that it works with the pure JS version of Highcharts. The solidgauge is well animated when data are updated.

**Comment by ppotaczek** [comment]
In the new version - 2.0.0 you can control the animation by `updateArgs` option. The order of arguments is the same as in basic `chart.update` method: https://api.highcharts.com/class-reference/Highcharts.Chart#update

`updateArgs={[true, true, true]}`

Live example: https://codesandbox.io/s/z6q506yo7m

**Comment by oleblaesing** [comment]
It seems that the problem with animated updates still exists in the current version. Even if I use the provided `updateArgs` in all variations. :/

Are there any twerks or progressions to solve this problem?

**Comment by ppotaczek** [comment]
Hi oleblaesing, 

I did not encounter any problems with animation in the current version. Could you create some live example to show the issue?

Best regards!

**Comment by oleblaesing** [comment]
It seems to be related with `datetime` xAxis. I provided a sandbox here, but in this example the growth itself isn't even working (notice that the state gets updated correctly): https://codesandbox.io/s/38xwxr81lp?autoresize=1&fontsize=14&hidenavigation=1

**Comment by ppotaczek** [comment]
@oleblaesing, 

If you call `setState` with a copy of the data, the animation works correctly:  https://codesandbox.io/s/6xv0kr3v0n

Let's continue the thread on stackoverflow in case of any additional questions.

Best regards!
