### ISSUE TITLE
afterSetExtremes raise event repeatly when it set a state

### ISSUE THREAD

**Issue by ledongthuc** [highcharts/highcharts-react#174]
I'm using with HighchartsReact 'stockChart' in my company to build stock history, but I got the problem when try to handle event afterSetExtremes.
It through events repeatedly if I try to set the state

Make a simple example here so you can check it 

https://stackblitz.com/edit/react-gdefuv?file=index.js

![Screen-Recording-2019-11-21-at-15 04 17](https://user-images.githubusercontent.com/1828895/69345197-069cd280-0c71-11ea-8ef4-c18dbaff9369.gif)

**Comment by ledongthuc** [comment]
A workaround solution I can do now is about adding a validation

```
eventHandler (param) => {
   if(this.state.min != param.min) {
      this.setState({ min: param.min });
   }
}
```

But I hope we have better solution from lib.

**Comment by ppotaczek** [comment]
Hi @ledongthuc,

Thank you for contacting us!

The problem is caused by updating chart repetitively on each `setState` call. If you have a static chart, the simplest solution is to set `allowChartUpdate` option to `false`. In other case, you should keep the chart options in the state.

**Live demo:** https://stackblitz.com/edit/react-c2lvrq?file=index.js
**Docs:** https://github.com/highcharts/highcharts-react#optimal-way-to-update

Best regards!

**Comment by ledongthuc** [comment]
Ah, unfortunately,  it's a dynamic chart. Maybe I must move the chart options in the state, and use the workaround to checking to make sure it doesn't update state many times. Anyway, thanks.
