### ISSUE TITLE
Maps in TypeScript

### ISSUE THREAD

**Issue by nguyendviet** [highcharts/highcharts-react#196]
I'm unable to build maps in TypeScript. If the `series type` is `'line'`, it works, but if it's 'map' or 'mapbubble' it doesn't. I've tried many different combinations of declaring the `chart`, `series` and `options` and one of them works.

```typescript
mport * as React from 'react';
import * as Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';

import map from "@highcharts/map-collection/custom/world.geo.json";

import HighchartsMap from "highcharts/modules/map";
import mapData from './mapData.json';

HighchartsMap(Highcharts);

// this throws error: Type '{ type: string; name: string; joinBy: string[]; data: { "code3": string; "z": number; "code": string; }[]; minSize: number; maxSize: string; tooltip: { pointFormat: string; }; }[]' is missing the following properties from type 'Series': chart, data, dataMax, dataMin, and 30 more.ts(2740)
const mapseries: Highcharts.Series = [{
    type: "mapline",
        name: "Population 2016",
        joinBy: ["iso-a3", "code3"],
        data: mapData,
        minSize: 4,
        maxSize: "12%",
        tooltip: {
          pointFormat: "{point.properties.hc-a2}: {point.z} thousands"
    }
}];

const chart: object = {
    borderWidth: 1,
    map: map
}

// this throws error: (Highmaps) Default mapData for all series. If set to a string, it functions as an index into the Highcharts.maps array. Otherwise it is interpreted as map data.
const mapOption: Highcharts.ChartOptions = {
    borderWidth: 1,
    map: map
}
const options: Highcharts.Options = {
    // if I include chart here: it throws error: (Highcharts, Highstock, Highmaps, Gantt) General options for the chart.
    title: {
      text: "World population 2013 by country"
    },
  
    subtitle: {
      text: "Demo of Highcharts map with bubbles"
    },
  
    legend: {
      enabled: false
    },
  
    mapNavigation: {
      enabled: true,
      buttonOptions: {
        verticalAlign: "bottom"
      }
    },
    // if I include series here, it throws error: (Highcharts, Highstock, Highmaps, Gantt) Series options for specific data and the data itself. In TypeScript you have to cast the series options to specific series types, to get all possible options for a series.
  };

export default function HighchartsTest(props: HighchartsReact.Props) {
    return (
        <div>
            <HighchartsReact
                constructorType={"mapChart"}
                chart={chart}
                highcharts={Highcharts}
                series={mapseries}
                options={options}
                {...props}
            />
        </div>
    )
}

```

**Comment by KacperMadej** [comment]
Hi @nguyendviet 

Thank you for contacting us about the problem. The problem is in this code line:

```ts
const mapseries: Highcharts.Series = [{
```

The type is not correct as this is an array with objects (well, in this case, a single object) and each of them is of type `Highcharts.Series` and to be more precise you could use map series type, so it will be  like: 

```ts
const mapseries: Array<Highcharts.MapLineSeries> = [{
```

or

```ts
const mapseries: Highcharts.MapLineSeries[] = [{
```

**Comment by nguyendviet** [comment]
Hi @KacperMadej ,

Thank you for your quick response. I've tried what you suggested and I get the error:
```
any
Namespace '"/.../node_modules/highcharts/highcharts"' has no exported member 'MapLineSeries'.ts(2694)
```

**Comment by KacperMadej** [comment]
Right, I have somehow missed that you have access only to the exported members - sorry about that.

Here's a tested example and a solution:

```ts

const series: Highcharts.SeriesMapOptions[] = [{
        type: 'map',
        mapData: mapDataWorld,
        data: data
    }];

const options: Highcharts.Options = {
    series: series
}
```

so you should be able to use `SeriesMapOptions[]` without any errors.

Depending on the IDE you are using you should be able to get some hints for TS definitions for the options you want to use. If the option is placed in the right part of the chart options object and works fine then it should be possible to highlight it or check the type of the object that you want to place as a separate variable, so that way you should be able to check what should be the type of the new variable. I hope this explanation is helpful, but if anything could be explained better please ask and I should be able to provide some code examples. Also, if you have any further problems please add a live demo, so it will be easier to check and edit the code.

**Comment by nguyendviet** [comment]
Thank you so much, @KacperMadej ! That works and it's similar to what I found [here](https://stackblitz.com/edit/react-ts-zs69rw?file=index.tsx), thanks to an answer [here](https://stackoverflow.com/questions/60046340/highcharts-map-with-react-typescript).
