### ISSUE TITLE
Word-break = break-all not working properly on chart labels

### ISSUE THREAD

**Issue by yanislavzagorov** [highcharts/highcharts-react#244]
Hi all! 

I have never managed to get break-all to work on chart labels when text-overflow is set to none. 

![image](https://user-images.githubusercontent.com/10464098/90341611-41197d00-e001-11ea-8569-04595f5ca276.png)

These labels have `word-break: break-all;` property, but the labels are still clipping into one another. I have tried setting useHtml to true for the xAxis to no avail. 

Any ideas? Seems like others have also had this issue before, with no clear answer.

**Comment by ppotaczek** [comment]
Hi @yanislavzagorov,

That issue is not related with our wrapper, so in the future for this kind of questions please use one of the support channels: https://www.highcharts.com/blog/support/

However, to break long words into several lines enable `useHTML` option and add the proper styles by CSS.

**Live example:** http://jsfiddle.net/BlackLabel/Ltmxp071/

Best regards!

**Comment by yanislavzagorov** [comment]
Thanks for your reply @ppotaczek! 

Unfortunately, I think the issue might indeed be related to the highcharts-react wrapped. I have gotten the word-break property to work using useHtml like you demonstrated on pure javascript, but I cannot make it work using highcharts-react.

If you have an example of this property working correctly in React, that would be much appreciated! 

Kind regards,

**Comment by yanislavzagorov** [comment]
Pardon, you are correct. I wasn't adding the !important property like a goof. 

Closing.
