### ISSUE TITLE
Warning: Lifecycle hook scheduled a cascading update

### ISSUE THREAD

**Issue by kate2811** [highcharts/highcharts-react#252]
I've faced with a notification in performance tab at Chrome DevTools. I use highcharts-react twise in my project and every chart causes this problem. 
<img width="670" alt="React App 2020-08-27 16-15-10" src="https://user-images.githubusercontent.com/43087418/91446959-c95d1500-e880-11ea-9d87-5cb8f36b9996.png">

**Comment by Basts** [comment]
@kate2811,

Thank you for contacting us!

First, I need to ask if you are sure that you are using our wrapper? I am asking because there is another popular wrapper on the npm created by the community - https://www.npmjs.com/package/react-highcharts.

If you are using our wrapper - are you able to reproduce this issue on the online editor which I will be able to debug? You can start from this template: https://stackblitz.com/edit/react-nwseym?file=index.js

**Comment by Basts** [comment]
Closed due to inactivity.
