### ISSUE TITLE
Updating chart events

### ISSUE THREAD

**Issue by iflp** [highcharts/highcharts-react#267]
Hi,

Can someone please help me to understand how would I go about updating values in an event? I need to reference my prop in the load and redraw event, but the value doesn't seem to update.

Problem reproduced here:
I expect to be able to toggle sort directions, my prop is updating correctly within the component but not the redraw event:
https://codesandbox.io/s/loving-heyrovsky-en9qb?file=/src/App.tsx

**Comment by ppotaczek** [comment]
Hi @iflp,

Thank you for contacting us!

The problem is that you change prop in `MyChart` component which trigger update of `HighchartsReact` component. In this case, chart options passed through the `options` prop are treated as completely new and the old event functions are overwritten.

The best solution seems to be keeping chart options in a state and directly calling `translateGraph`, not by using events.

```
  React.useEffect(() => {
    if (chartRef.current) {
      translateGraph.call(chartRef.current.chart)
    }
  }, [sortDir]);
```

**Live demo:** https://codesandbox.io/s/pedantic-violet-mbiq1?file=/src/App.tsx

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
