### ISSUE TITLE
using createRef causes nav handles to disappear, like so much cheap wine 

### ISSUE THREAD

**Issue by craig-harbottle** [highcharts/highcharts-react#287]
Hi, using `createRef` (as recommended in the docs) causes the navigator handles to disappear when they are dragged - at least in the demo I've provided.
 
However, with `useRef` it works as expected.  

Here's a [sandbox](https://codesandbox.io/s/dank-bird-8ln7l?file=/src/App.js) to give a simple demo of what I'm trying to do (basically a zoom btn that sits outside the chart). 

Perhaps this is not the correct way to do something like this? Or should I be using `useRef`. I'd assume I should be using this for a functional component. But the type definition and the docs make me think not. 

Thanks in advance :-)

**Comment by ppotaczek** [comment]
Hi @craig-harbottle,

Thank you for contacting us!

You are right, you should use `useRef` instead of `createRef`. Maybe it is unclear, so I will improve the docs.
However, to avoid unnecessary update, I recommend to keep chart options in a state, so something like this: https://codesandbox.io/s/great-poincare-0527u?file=/src/App.js should work better.

Best regards!

**Comment by craig-harbottle** [comment]
Thanks @ppotaczek
