### ISSUE TITLE
Indicators

### ISSUE THREAD

**Issue by boriswexler** [highcharts/highcharts-react#3]
I am having trouble getting indicators to work. I have imported highstock-release, but an getting an error #17 when I try to add an indicator. Here are my imports and base code:

```
import Highcharts from 'highcharts/highstock'
import HighstockRelease from 'highstock-release'
import HighchartsReact from 'highcharts-react-official'


....


<HighchartsReact highcharts={Highcharts}
                              constructorType={'stockChart'}
                              options={this.state.config}></HighchartsReact>
```

Would appreciate any help - thanks!

**Comment by KacperMadej** [comment]
Hi @boriswexler 

The highstock-release is depreciated.
For indicators you need to load base of indicators: https://unpkg.com/highcharts@6.0.4/indicators/indicators.js,
e.g. like:
`import HSIndicators from 'highcharts/indicators/indicators.js'`
and an indicator that you want to use. Let's say you want to use [`cci`](https://unpkg.com/highcharts@6.0.4/indicators/cci.js), then use:
`import HScci from 'highcharts/indicators/cci.js`
Next, make sure to init them in correct order on Highstock instance.
Like seen [here in demo code](https://github.com/highcharts/highcharts-react/blob/master/demo/demo.jsx#L4-L15), but use `highcharts` NPM package since `highstock-dist` is depreciated.

All indicators files are here: https://github.com/highcharts/highcharts-dist/tree/master/indicators

Please let me know if you have any more questions.
The info here should resolve the problem you have, but I would like to keep the issue open until the demo and docs will be update.

**Comment by boriswexler** [comment]
Thank you. I resolved the issue - figured out that highstocks-release was
deprecated and got it to work. I do appreciate the help!

**Comment by freddysu** [comment]
@boriswexler @KacperMadej 
Hello, may I ask how do you resolve the issue?
I use highcharts 6.0.7 and tried to import

```
import Highcharts from 'highcharts/highstock';
import HSIndicators from 'highcharts/indicators/indicators.js'
```

But still get error #17 when I add type: 'sma' into my chart option.
Could u please help me with this and hopefully provide more details on how u resolved the issue.
Thanks a lot!

**Comment by KacperMadej** [comment]
@freddysu 

Please remember about initialization when using only `import`. Code like this should work fine:

```js
import Highcharts from 'highcharts/highstock';
import HSIndicators from 'highcharts/indicators/indicators.js'
HSIndicators(Highcharts)
```

If this doesn't help please provide minimal demo.

**Comment by freddysu** [comment]
@KacperMadej 
Thanks for the replying!
It turns out that I use react-highcharts so I have to pass it rather than Highcharts as a param then it works!
```
import ReactHighstock from 'react-highcharts/ReactHighstock.src';
import Indicators from 'highcharts/indicators/indicators';
Indicators(ReactHighstock.Highcharts);
```
or
```
import ReactHighstock from 'react-highcharts/ReactHighstock.src'; require('highcharts/indicators/indicators.js')(ReactHighstock.Highcharts);
```

But now I got another issue. I cannot get SMA to work with dataGrouping as I posted it on stackoverflow. 
Here's the link:
https://stackoverflow.com/questions/48879214/highstock-sma-simple-moving-average-datagrouping-not-working

Would you mind to have a look and help me?:)
Appreciate!!

**Comment by pawelfus** [comment]
Hi @freddysu 

It's a bug in the indicators plugin, see https://github.com/highcharts/highcharts/issues/7823

**Comment by freddysu** [comment]
@pawelfus 
The workaround works! Thank you so much!!
