### ISSUE TITLE
unable to dynamically update plot lines using svgElem.translate (Error: <path> attribute d: Expected number,)

### ISSUE THREAD

**Issue by abhimanusharma** [highcharts/highcharts-react#347]
Here is the [working demo](http://jsfiddle.net/abhimanusharma/25ashpbz/6/) 

When I am trying to use same example in my code, while dragging I am getting this error.
![screenshot-nimbus-capture-2021 12 29-14_51_06](https://user-images.githubusercontent.com/5707050/147647494-97b6c8a3-c53c-4dcb-a770-5122c1815b55.png)

Mentioned line number code is as below.
```javascript
if(upperLine) {
        new_translation = axis.toPixels(new_value_to + axis.toValue(0) - plotBand.options.to);
        newPath[2] = axis.toPixels(plotBand.options.from) - new_translation;
        newPath[5] = axis.toPixels(plotBand.options.from) - new_translation;
        newPath[2] = Number(newPath[2]);
        newPath[5] = Number(newPath[5]);
      } else {
        new_translation = axis.toPixels(new_value_from + axis.toValue(0) - plotBand.options.from);
        newPath[7] = axis.toPixels(plotBand.options.to) - new_translation;
        newPath[9] = axis.toPixels(plotBand.options.to) - new_translation;
        newPath[7] = Number(newPath[7]);
        newPath[9] = Number(newPath[9]);
      }
      console.log('path',newPath);
      
      newPath = newPath.join(" ");
      plotBand.svgElem.attr('d', newPath);
      
      plotBand.svgElem.translate(
        axis.horiz ? new_translation : 0,
        axis.horiz ? 0 : new_translation
      );
```

**Comment by ppotaczek** [comment]
Hi @abhimanusharma,

We use this repository as a bug tracker for the highcharts-react wrapper. Please use one of our support channels: https://www.highcharts.com/blog/support/ for questions related with Highcharts.

However, I can see that the error occurs only if you move the left border of the plot band and it is caused by:

Right border: `M 203.5 200.2 L 203.5 200.2 L 311.5 326 L 311.5 46 Z` -> correct
Left border: `M 230.5 46 L 230.5 326 L 330.5 326 330.5 307.5 46 Z` -> odd number of values after the last L

Best regards!
