### ISSUE TITLE
Unable to access series data from chart.series.options.data

### ISSUE THREAD

**Issue by abhimanusharma** [highcharts/highcharts-react#348]
Here is my ts code.
```javascript
const series = chart?.series;
console.log('series', series ? series[0] :null);
console.log('series.data', series ? series[0].data :null);
console.log('option', series ? series[0].options.data :null);
```

Getting below error
```shell
Property 'data' does not exist on type 'SeriesOptionsType'.
Property 'data' does not exist on type 'SeriesAbandsOptions'.ts(2339)
```

But in my console I am getting data property in options if I run like this.
`console.log(chart.series[0].options)`
![chart series options data](https://user-images.githubusercontent.com/5707050/147673679-5ef73545-dd2c-426b-b6c2-b9d65a2faff2.png)

**Comment by ppotaczek** [comment]
Hi @abhimanusharma,

We use this repository as a bug tracker for the highcharts-react wrapper. Please use one of our support channels: https://www.highcharts.com/blog/support/ for questions related with Highcharts.

However, I can see that the error occurs only if you move the left border of the plot band and it is caused by:

Right border: `M 203.5 200.2 L 203.5 200.2 L 311.5 326 L 311.5 46 Z` -> correct
Left border: `M 230.5 46 L 230.5 326 L 330.5 326 330.5 307.5 46 Z` -> odd number of values after the last L

Best regards!

**Comment by ppotaczek** [comment]
Hello @abhimanusharma, 

Please check this related issue: https://github.com/highcharts/highcharts/issues/13373

You need to check the series type:

```
if (series?.[0].options.type === "line") {
  console.log("series", series ? series[0] : null);
  console.log("series.data", series ? series[0].data : null);
  console.log("option", series ? series[0].options.data : null);
 }
```

**Live demo:** https://codesandbox.io/s/react-typescrip-qsjpk?file=/src/App.tsx
