### ISSUE TITLE
Highcharts.charts does not remove chart properly on unmount

### ISSUE THREAD

**Issue by justduy** [highcharts/highcharts-react#39]
The Highcharts instance does not properly remove the chart from the charts array, leaving me with a
`Highcharts.charts = [undefined]`. And as I  navigate through routing e.g `history.push("/graph")`, it keeps adding undefined objects once you move away from the component. So the new initialized chart will be at the end of the array.

**Comment by KacperMadej** [comment]
Hi @justduy 

The behavior is know and the feature works like that by design in core, pure JavaScirpt Highcharts library. There's nothing wrong with this - this is how it works, and the highcharts-react doesn't changes anything in this matter.

It's not a highcharts-react issue - please contact [Highcharts support for technical support](https://www.highcharts.com/support).
