### ISSUE TITLE
highchart map tooltip wrong position for low width desktop

### ISSUE THREAD

**Issue by iamsurajshinde** [highcharts/highcharts-react#428]
highcharts map tooltip wrong position for a low-width desktop. for the big screen, it's showing proper position

**Comment by ppotaczek** [comment]
Hi @iamsurajshinde, 

Thank you for contacting us!

I didn't encounter such a problem with using Highcharts and our wrapper, so please provide more information about the issue and try to reproduce it in some online code editor (you can start from: https://codesandbox.io/s/highcharts-react-demo-forked-gbg3n3).

However, this problem is probably related to the main Highcharts repository, so you should create your issue here:  https://github.com/highcharts/highcharts/issues

Best regards!

**Comment by iamsurajshinde** [comment]
Thanks
