### ISSUE TITLE
Wrong color type in SeriesNetworkgraphNodesOptions

### ISSUE THREAD

**Issue by impact-ls** [highcharts/highcharts-react#440]
I am trying to use gradient colors in `networkgraph` for nodes. The code works, but due to the wrong type definition, I am getting a TypeError.

![image](https://github.com/highcharts/highcharts-react/assets/136742598/c6e9392e-fbf3-48e6-a835-5919e17b43c3)
![image](https://github.com/highcharts/highcharts-react/assets/136742598/dab067c9-d2fb-4a5d-94fd-10777ed66546)
<img width="562" alt="image" src="https://github.com/highcharts/highcharts-react/assets/136742598/72e209a1-8a07-4862-a5b7-471599bc6e9c">

```json
    "highcharts": "^11.2.0",
    "highcharts-react-official": "^3.2.1",

**Comment by ppotaczek** [comment]
Hi @impact-ls,

Thank you for contacting us!

This issue is related to Highcharts, not to the `highcharts-react-offical` wrapper, so you should report it on the main repository: https://github.com/highcharts/highcharts/issues

However, I see that the error is consistent with API documentation: https://api.highcharts.com/highcharts/series.networkgraph.nodes.color

As a quick workaround, you can use `any` type:

```
  series: [
    {
      type: 'networkgraph',
      nodes: [{
        color: {
          linearGradient: { x1: 0, x2: 0, y1: 0, y2: 1 },
          stops: [
              [0, '#003399'], // start
              [0.5, '#ffffff'], // middle
              [1, '#3366AA'] // end
          ]
        } as any
      }],
      ...
    }
  ]
```

**Live example:** https://stackblitz.com/edit/react-starter-typescript-2gfpyg

Best regards!
