### ISSUE TITLE
Wrong Gantt Behaviour On Having Multiple Ids in Series Data. 

### ISSUE THREAD

**Issue by rolandvincze** [highcharts/highcharts-react#452]
### Description
In the provided [example](https://codesandbox.io/p/sandbox/gantt-simple-click-forked-p6kksx?file=%2Fsrc%2FApp.js), we implemented a gantt chart where initially the series data was rendered correctly even though some ids were duplicate.

### Steps to reproduce
Observe how all the gantt bars are rendered initially.
Trigger a re-render on the component (by clicking on any of the gantt in our case).
Note that the series that have duplicate ids render only the last set of data [example](https://codesandbox.io/p/sandbox/gantt-simple-click-forked-p6kksx?file=%2Fsrc%2FApp.js).

### Expected Behavior
When triggering a re-render, the component should either re-render the series correctly (consistent behaviour)
or give an error from the start that the user has data with duplicate ids in his/her series.

### Actual Behavior
When re-rendering the chart, only the data of the last are re-rendered.

### Relevant Screenshots

before
![image](https://github.com/highcharts/highcharts-react/assets/141722571/3c5270b0-b789-4e56-8b1c-b69cd53cf4de)

after
![image](https://github.com/highcharts/highcharts-react/assets/141722571/84c0171c-fc94-4193-8a2a-7dcf8abd6fb0)

**Comment by KamilKubik** [comment]
Hello [rolandvincze](https://github.com/rolandvincze),

Thanks for contacting us and bringing up this problem!

By default, Highcharts creates a reference to the provided data, not a direct copy, so data points seem overridden during the rerenders after the initial one. Nevertheless, I wouldn't classify it as a bug since by definition `id` should be a unique value that Highcharts handles as expected. I'd also expect a warning message in the console indicating that using the repeated IDs may lead to some unexpected behaviors. Since the change should be made to the Highcharts core code, feel free to report it [here](https://github.com/highcharts/highcharts/issues/new/choose).

What you can do is change the Highcharts's initial data mutation by using the **chart.allowMutatingData** property set to _false_ to create a direct copy of the provided data. Please refer to your updated [example](https://codesandbox.io/p/sandbox/gantt-simple-click-forked-9kvr59?file=%2Fsrc%2FApp.js) and the API [reference](https://api.highcharts.com/gantt/chart.allowMutatingData).

Kind Regards!

**Comment by rolandvincze** [comment]
Hi @KamilKubik,

Thank you for the answer! I would have another question regarding this, does this change come with any other side effect besides possible performance issues? (I'm interested in side-effects functionality-wise mainly).

Kind Regards!
