### ISSUE TITLE
Updating a column chart's series data with dataSorting: enabled causes a crash

### ISSUE THREAD

**Issue by jonatanjohnsson** [highcharts/highcharts-react#473]
(unsure if I should report here or the highcharts repo, but starting here)

**Example that causes the crash:**
Forked "Optimal way to update with React Hook" example from highcharts-react-official:
https://stackblitz.com/edit/react-8wujtj?file=index.js

**Description**
Updating the chart with the provided data causes a crash. I have other similar data updates (with many more points) that work well, but this specific change in data somehow, for some reason, causes a crash - and I am unable to determine why.
I believe it is somehow related to `dataSorting: enabled`. 

**Crash error messages**
<img width="504" alt="image" src="https://github.com/highcharts/highcharts-react/assets/9350321/e49854bd-4e25-4db8-ae56-4ba7a7524124">

**Notes and variants that work**
This example, not using hooks, but with the same data and update, works well:
https://stackblitz.com/edit/react-k1slzu?file=index.js

If I disable animations, it doesn't crash. 
If I add unique ids to the series on each update, it doesn't crash.

**Thoughts**
Have I missed something in the documentation indicating that my approach to updating like this is wrong, and can not be done?

Thank you.

**Comment by ppotaczek** [comment]
Hi @jonatanjohnsson,

Thank you for contacting us! 

There are used two different versions of Highcharts in the provided examples - 8.0.0 and 7.03. The data sorting feature has been added in v8.0.0 and that's why there is no errors in v7.03. 

Another thing is that in v10.1.0 the `allowMutatingData` option has been added, which also prevents the error, but causes data-sorting to work differently.

Highcharts changelog: https://www.highcharts.com/changelog/#highcharts-v10.1.0

However, the main problem looks like a bug in Highcharts, it can be reproduced in pure JS and still occurs in the newest Highcharts version: https://jsfiddle.net/BlackLabel/p7sqd0n5/, so please report it on the main Highcharts repository: https://github.com/highcharts/highcharts/issues/new/choose

Best regards!

**Comment by jonatanjohnsson** [comment]
@ppotaczek Thank you very much for the reply. I'm sorry about the versioning confusion, but I am happy that you were able to confirm the bug nonetheless.

As this isn't relevant to this repo I'll be closing this issue.
For any future reference, here's the issue I posted in highcharts:

https://github.com/highcharts/highcharts/issues/21173
