### ISSUE TITLE
Issue: Inconsistent Space Between Axis and Scroll Bar When Scrolling and Zooming in Chart

### ISSUE THREAD

**Issue by Satyam7Jha** [highcharts/highcharts-react#478]
**Description:**
We have added a scroll feature to our chart, but we are facing an issue. When we scroll and zoom in on the chart, the space between the axis and the scroll bar changes significantly and is not consistent.

**Implementation** : https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-jqykd9?file=%2Fdemo.jsx

**Steps to Reproduce:**
1. Add scroll functionality to the chart.
2. Scroll and zoom in on the chart.
3. Observe the space between the axis and the scroll bar. 

  **Attachments:**
  
  on scroll

https://github.com/highcharts/highcharts-react/assets/75986382/28beeda5-d02d-4d4a-b4e3-518333f82b63

on zomm

https://github.com/highcharts/highcharts-react/assets/75986382/dc7ddc71-1281-4adb-a9d7-f6536be01ddb

**Comment by Satyam7Jha** [comment]
Hey @KamilKubik 
I used scrollablePlotArea to resolve the scrolling issue, as you can see in the video below:

https://github.com/highcharts/highcharts-react/assets/75986382/7733537c-57dc-4ee8-a53a-9da651d88236

However, could you please show me how to update the color of the transparent layer on the axis?

Axis Transparent Layer

<img width="1244" alt="image" src="https://github.com/highcharts/highcharts-react/assets/75986382/77afbdef-e9bc-4e4f-959d-dc3f626fc7e7">

Thanks

**Comment by KamilKubik** [comment]
Hello [Satyam7Jha](https://github.com/Satyam7Jha),

Thank you for contacting us again!

I'm glad you made it work. Since we operate on the custom labels, the `scrollablePlotArea` property seems the most appropriate.

According to the transparent layout, it should be transparent by default, and you can operate over its [opacity](https://api.highcharts.com/highcharts/chart.scrollablePlotArea.opacity) to match it to the plot background: [demo](https://jsfiddle.net/BlackLabel/uzt6jxap/), or overlap the plot to make the chart looks as normal: [demo](https://jsfiddle.net/BlackLabel/nqzx41m3/).

I can see the layer is darker in your case, can you share your chart's configuration if the above doesn't help? 

Kind Regards!

**Comment by KamilKubik** [comment]
Closed due to inactivity.
