### ISSUE TITLE
Charts resize infinitely when placed under a flexbox with flex-direction: column

### ISSUE THREAD

**Issue by wctiger** [highcharts/highcharts-react#483]
## Reproduce link
https://stackblitz.com/edit/highcharts-react-template-9oig96?file=src%2FApp.js
## Steps to reproduce
1. Set a chart to fill its container height using the `containerProps` suggested in https://github.com/highcharts/highcharts-react/issues/72
2. Set the container style as a vertical flexbox: `<div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}> ` 
3. Insert a div without explicit height props between the container and the chart
4. Add an arbitrary element above the chart 
5. Resize the width of the container, and the chart will start to self-resize its height infinitely 
## Expected behavior 
I understand this set up is problematic as the container with explicit height is supposed to be direct parent of the chart. However highcharts should not resize infinitely but either do nothing or fail with an explicit error

**Comment by KamilKubik** [comment]
Hello [wctiger](https://github.com/wctiger)!

Thanks for bringing up this issue, I agree it shouldn't resize the chart infinitely no matter the outer elements.

I did some more debugging, and it seems there's a problem with the [reflow](https://github.com/highcharts/highcharts/blob/master/ts/Core/Chart/Chart.ts#L1768) method in the Highcharts Core code. Since it's not directly related to the React integration, I highly encourage you to follow [this](https://github.com/highcharts/highcharts/issues/21510) thread for any further information.

My apologies for the inconvenience,
Kind Regards!
