### ISSUE TITLE
How to add new y axis?

### ISSUE THREAD

**Issue by CITIZENDOT** [highcharts/highcharts-react#485]
I tried adding new series (`rsi`) like below, but I'm getting error-18 (The requested axis does not exist)

```typescript
[
  {
    type: "candlestick",
    id: "DEFAULT",
    name: "DEFAULT",
    data: [],
    yAxis: 0,
  },
  {
    type: "column",
    id: "volume",
    name: "Volume",
    data: [],
    yAxis: 1,
  },
  {
    type: "rsi",
    id: "rsi",
    linkedTo: "DEFAULT",
    yAxis: 2,
  },
];

```

**Comment by KamilKubik** [comment]
Hello [CITIZENDOT](https://github.com/CITIZENDOT)!

Thanks for contacting us.

By default, the stock chart has two y-axes, one for the series and one for the navigator (assuming it's not disabled), so for series like `candlestick`, `volume`, or `rsi` there's one y-axis only (by default). You can point every series to the particular y-axis using the `yAxis` property as you did, and their indices start from `0`, which is also a default value if you don't define it. The issue is that you're referring to the `1`, and `2` y-axes that don't exist. You can either point all the series to the one y-axis like [this](https://stackblitz.com/edit/react-w91lx6?file=index.js) or define additional ones, [example](https://stackblitz.com/edit/react-dbhwb5?file=index.js) (configuration taken from your comment). 

What's more, to use the `rsi` series, you have to define both [indicators](https://code.highcharts.com/stock/indicators/indicators.js) and [rsi](https://code.highcharts.com/stock/indicators/rsi.js) modules as shown in the above examples. 

Let me know how it works for you,
Kind Regards!

**Comment by KamilKubik** [comment]
Closed due to inactivity.
