### ISSUE TITLE
Axis Alignment and Tooltip Issues with Highcharts Stock Scroll

### ISSUE THREAD

**Issue by Satyam7Jha** [highcharts/highcharts-react#493]
Description
When implementing the Highcharts/Stock scroll feature, two main issues are occurring:

The y-axis is not aligning and displaying properly.
Unwanted tooltips are appearing at the bottom of columns for the axis.

Expected Behavior (non highchart/stock)

<img width="1718" alt="Screenshot 2024-09-01 at 2 22 16 AM" src="https://github.com/user-attachments/assets/73624616-23e9-4dd2-90d6-9eb8de3b16f1">

The axis should be properly aligned and visible.
Only the default tooltip (as seen in the non-stock version) should be displayed.

Current Behavior with highchart/stock

https://github.com/user-attachments/assets/b8c0128f-42e8-44e0-a583-927d1a44cf97

The y-axis is misaligned and not displaying correctly with Stock scroll enabled.
Additional, unwanted tooltips are appearing at the bottom of columns for the axis.

Code-sandbox: https://codesandbox.io/p/github/Satyam7Jha/visualization/main?import=true&embed=1&showConsole=true

**Comment by KamilKubik** [comment]
Hello @Satyam7Jha,

Thanks for contacting us again!

According to the wrong y-axis labels display, the issue occurs because of the offset set by the [yAxis.labels.x](https://api.highcharts.com/highstock/yAxis.labels.x) property set to `20` in your configuration. You can test it by decreasing this value as the labels are moved to the right. I assume the property should be removed to meet your requirements. 

The second (bottom) tooltip is a default stock charts feature that in your implementation shows the x-axis values. You can disable it by setting the [tooltip.headerFormat](https://api.highcharts.com/highstock/tooltip.headerFormat) property to `undefined` or an empty string. 

Here's your [demo](https://codesandbox.io/p/github/Satyam7Jha/visualization/csb-lznykg/draft/laughing-pond?embed=1&import=true&showConsole=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxk1quk700062e692h9icpws%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxk1quk700022e69xb83o8hk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxk1quk700042e69a81uzpns%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxk1quk700052e69q1hsk0gt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxk1quk700022e69xb83o8hk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxk1quk700012e694zx3uij9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxmxbgoj00022e69602y03zg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A271%252C%2522startColumn%2522%253A8%252C%2522endLineNumber%2522%253A271%252C%2522endColumn%2522%253A8%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcharts%252Fhooks%252Fuse-column-chart-with-scoll-option.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxn2jli400022e6anrrbwsnl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A79%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A79%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxn3aa5f00022e6a68880tia%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A57%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A66%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fhighcharts%252Fbase-chart.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly5jgfwr00022e6a299e6xnh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A4%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A4%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.css%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxk1quk700022e69xb83o8hk%2522%252C%2522activeTabId%2522%253A%2522clxn3aa5f00022e6a68880tia%2522%257D%252C%2522clxk1quk700052e69q1hsk0gt%2522%253A%257B%2522id%2522%253A%2522clxk1quk700052e69q1hsk0gt%2522%252C%2522activeTabId%2522%253A%2522cm09gszjx00282e69gdkb4bm8%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cly5jeig400hs2e6a2uwfs5cc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522cly5jgje800082e6azy0f5110%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522cly5jgje800092e6av5dy3u06%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cly5jgt2l00132e6aknj37viy%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clz2fsqlo000t2e6acvj0z4px%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522cm03bau0g00072e6a4mzbjf3z%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cm09gszjx00282e69gdkb4bm8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxk1quk700042e69a81uzpns%2522%253A%257B%2522id%2522%253A%2522clxk1quk700042e69a81uzpns%2522%252C%2522activeTabId%2522%253A%2522cly5je9rl00f92e6aq1ql27jf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522cly5jds6v008w2e6a4gpq2dcz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cly5je9rl00f92e6aq1ql27jf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) updated with the above changes. 

Kind Regards!

**Comment by Satyam7Jha** [comment]
could you please make demo link public, thanks

**Comment by KamilKubik** [comment]
@Satyam7Jha I created a new branch when I added the changes. It's created based on your public project, so it should be publicly accessible (I also tested it on different devices). Kindly refer to the shared button copied link [demo](https://codesandbox.io/p/github/Satyam7Jha/visualization/csb-lznykg/draft/laughing-pond?embed=1&import=true&showConsole=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxk1quk700062e692h9icpws%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxk1quk700022e69xb83o8hk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxk1quk700042e69a81uzpns%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxk1quk700052e69q1hsk0gt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxk1quk700022e69xb83o8hk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxk1quk700012e694zx3uij9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxmxbgoj00022e69602y03zg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A271%252C%2522startColumn%2522%253A8%252C%2522endLineNumber%2522%253A271%252C%2522endColumn%2522%253A8%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcharts%252Fhooks%252Fuse-column-chart-with-scoll-option.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxn2jli400022e6anrrbwsnl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A79%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A79%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxn3aa5f00022e6a68880tia%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A57%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A66%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fhighcharts%252Fbase-chart.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly5jgfwr00022e6a299e6xnh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A4%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A4%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.css%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxk1quk700022e69xb83o8hk%2522%252C%2522activeTabId%2522%253A%2522clxn3aa5f00022e6a68880tia%2522%257D%252C%2522clxk1quk700052e69q1hsk0gt%2522%253A%257B%2522id%2522%253A%2522clxk1quk700052e69q1hsk0gt%2522%252C%2522activeTabId%2522%253A%2522cm09gszjx00282e69gdkb4bm8%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cly5jeig400hs2e6a2uwfs5cc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522cly5jgje800082e6azy0f5110%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522cly5jgje800092e6av5dy3u06%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cly5jgt2l00132e6aknj37viy%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clz2fsqlo000t2e6acvj0z4px%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522cm03bau0g00072e6a4mzbjf3z%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cm09gszjx00282e69gdkb4bm8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxk1quk700042e69a81uzpns%2522%253A%257B%2522id%2522%253A%2522clxk1quk700042e69a81uzpns%2522%252C%2522activeTabId%2522%253A%2522cly5je9rl00f92e6aq1ql27jf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522cly5jds6v008w2e6a4gpq2dcz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cly5je9rl00f92e6aq1ql27jf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), and the one directly from the URL: https://codesandbox.io/p/github/Satyam7Jha/visualization/csb-lznykg/draft/laughing-pond?embed=1&import=true&showConsole=true. 

Also, I can't fork this project into my team. Could you share the Codesandbox error if you're still unable to open it? 

According to the mispositioned y-axis label, the last y-axis label is hidden by default so it's not positioned properly/visible. You can adjust its visibility using the [yAxis.showLastLabel](https://api.highcharts.com/highstock/yAxis.showLastLabel) property (as you can see it's `undefined` by default). I set it to `true` in the above demo (the problem shouldn't occur). Nevertheless, if you'd like to keep it hidden, I can see it renders beyond the viewport in some cases, but without any unwanted effect to the layout. Feel free to let me know if you face any difficulties with that.

Let me know how the above works for you,
Kind Regards!
