### ISSUE TITLE
 Charts with responsiveness rule and boost activated, when updated they cause an internal error

### ISSUE THREAD

**Issue by guilhermealbanaz** [highcharts/highcharts-react#495]
**Details**

I have attached a GIF (problem.gif) demonstrating the issue I am encountering. In Example 1, we are importing the series, which seems to prevent the error from occurring. In contrast, Example 2, which does not import the series, encounters the error. It appears that following the responsibility rule for removal resolves the issue in Example 2 as well

![problem](https://github.com/user-attachments/assets/f36474a1-f90e-4cfd-b690-d1b31d2daaa3)

I was able to conduct that this particular issue is reproducible only when used with Highcharts React integration and also when the series options are changed on responsive condition, e.g. groupPadding or pointPadding. If you change the title of chart instead of changing groupPadding, it won't throw an error immediately. 

**Demo in vanilla JS:** https://jsfiddle.net/BlackLabel/sh3dybaf/  

**Expected behaviour**
charts with responsiveness rule and boost activated, when updated they should not cause an error

**Actual behaviour**
charts with responsiveness rule and boost activated, when updated they cause an internal error

**Live demo with steps to reproduce**
https://codesandbox.io/p/sandbox/elastic-cannon-6vdnlg?file=%2Fsrc%2Findex.tsx%3A12%2C5

A workaround to this problem would be to set the immutable property on the chart constructor as true.

**Product version**
- Highcharts - 11.4.7

**Affected browser(s)**
- Chrome (127)

**Comment by KamilKubik** [comment]
Hello [guilhermealbanaz](https://github.com/guilhermealbanaz),

Thanks for contacting us again and reporting this!

I was able to reproduce it beyond the React integration, and I reported it [here](https://github.com/highcharts/highcharts/issues/21841). Since it's not directly related to the React integration, I highly encourage you to follow the reported thread where all the further information will be provided.

Using the `immutable` parameter seems to work, but it recreates the chart on every rerender so it may not be the most efficient solution. Alternatively, you can memoize the options object by keeping the same reference in the memory, so it'll not update on every component rerender. Kindly refer to your updated [demo](https://codesandbox.io/p/sandbox/affectionate-gould-nczdcq?workspaceId=e204a32a-9996-4c96-b99d-9fe3d6fc96d0&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm111dbiz00073b6lx9pr0muu%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm111dbiz00033b6l6z9rql6g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm111dbiz00043b6l576x44ur%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm111dbiz00063b6l0dy7buf7%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm111dbiz00033b6l6z9rql6g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm111dbiz00023b6lz7f4af8l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm12behze00023b6lgydri4rd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A372%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A372%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FExample2.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm111dbiz00033b6l6z9rql6g%2522%252C%2522activeTabId%2522%253A%2522cm12behze00023b6lgydri4rd%2522%257D%252C%2522cm111dbiz00063b6l0dy7buf7%2522%253A%257B%2522id%2522%253A%2522cm111dbiz00063b6l0dy7buf7%2522%252C%2522activeTabId%2522%253A%2522cm12bfxc5000t3b6ry6t2ni2x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm111dbiz00053b6lbg07pjx8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm111e6g100143b6lz0iy6nfk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm12belwc00133b6l4pe5u3yf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm12bfxc5000t3b6ry6t2ni2x%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm111dbiz00043b6l576x44ur%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm111dbiz00043b6l576x44ur%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Also, I'd like to point you to the [error](https://assets.highcharts.com/errors/12/) visible in the console, standing for the proper data formatting and [turboThreshold](https://api.highcharts.com/highcharts/plotOptions.series.turboThreshold) property usage for the boost mode. 

Kind Regards!

**Comment by KamilKubik** [comment]
Closed due to inactivity.
