### ISSUE TITLE
different types of parameter for chart.showLoading()

### ISSUE THREAD

**Issue by qj10aw** [highcharts/highcharts-react#503]
This maybe a feature request for `chart.showLoading`, to accept different types of parameter other than text string. ie. `JSX.Element`

I'm currently using : 
- highcharts 10.3.3
- highcharts-react-official 3.2.1

I have been using `chart.showLoading()` to display the default 'Loading...' message while the chart data is loading.
But I have a specific requirement to replace that text with a Spinner, which is a react component.
I want it to be just like the existing 'Loading...' text by the `showLoading()`, but currently `showLoading()` only accepts string.

Would you please consider to have `chart.showLoading()` to accept a parameter other than string? such as a JSX.Element, so we can have a react component instead of that simple text.

I've been trying suggested workaround in the README [here](https://github.com/highcharts/highcharts-react?tab=readme-ov-file#how-to-add-react-component-to-a-charts-element), with ReactDOM.createPortal and referencing live [demo](https://codesandbox.io/s/1o5y7r31k3), but so far not successful. It seems it just does not apply to the load event.

Please let us know if this could be possible, or I'd love to try any other workaround.

(Or, please also consider having a functionality to show spinner instead of text in highchart in general..?)

Thank you

**Comment by KamilKubik** [comment]
Hi [qj10aw](https://github.com/qj10aw)!

Thanks for reporting this!

We're working on a more generative version of our integration, which you can see in our [roadmap](https://www.highcharts.com/roadmap/). I agree we should treat it as a feature request, and I reported this internally. 

As a workaround, you can either overlap the chart with your custom element (displaying the loader) or adjust the `showLoading` method to render a custom React component. Kindly refer to the [demo](https://stackblitz.com/edit/react-txel88yk?file=index.js,index.html,package.json). 

Note that Highcharts renders both the `highcharts-loading` container div element, which works as an overlay (different opacity) and the `highcharts-loading-inner` span element, which displays a provided text (in the above demo, I removed the `highcharts-loading-inner` span element completely). You should follow the same approach using the React Portals and render the custom React component under the `highcharts-loading` container div element. Nevertheless, this solution seems less efficient, as you can manipulate the elements after they have been rendered, rather than adjusting them during creation (as shown in the above demo). 

Kind Regards!

**Comment by qj10aw** [comment]
Hi, Thanks for the answer and the actual example demo!
Before, I've been trying with this method (this [demo](https://stackblitz.com/edit/react-x46b78?file=index.js) provided at the end of this [thread](https://www.highcharts.com/forum/viewtopic.php?t=46014) )
This was to have a Spinner component alongside with the chart, - and it worked fine as I intended.

And now I applied the demo you provided here - thanks again! - and it also works great, except for the fading effect. It seems the original dimming out-then-in effect of [`chart.showLoading`](https://api.highcharts.com/class-reference/Highcharts.Chart#showLoading) got lost with this functionality extension. As a result, the previous plots in the chart container remain very vivid, together with the loading spinner, until the new data finally loads with the new plot, which would be confusing to the user. I tried adding `css(chart.container, { opacity: 0.5 });` or `animate(chart.container, { opacity: 0.5 })`... etc, but so far unsucessful. I'll keep trying different methods to complement this. 

Thanks for the feedback, looking forward to seeing the roadmap to be coming!

**Comment by KamilKubik** [comment]
I'm glad you found it helpful!

I'm not entirely sure if I understood your point. If you look at the provided [demo](https://stackblitz.com/edit/react-txel88yk?file=index.js), the `highcharts-loading` container div element remains the same, providing the original "shadow/fading" effect (I'm attaching the screen with this element highlighted). 

![Screenshot 2024-12-13 at 10 37 31](https://github.com/user-attachments/assets/9a17c5e5-61b6-42c5-99b5-9c6898aa266b)

Also, you can adjust this container by changing the `loadingOptions.style` object (it contains visual styles like `opacity`). 

If you don't find it helpful, may I ask what effect would you like to achieve with the overlapping "shadow/fading" container? 

Regards!

**Comment by qj10aw** [comment]
Hi, thanks for pointing out the div! Sorry, my bad that I didn't inspect it thoroughly. I had a type descrepancy while setting the dimensions so the correct size for the div was not applying. Resolved that with some type casting and now it works fine. 
Really appreciate all of this, thanks a lot!
