### ISSUE TITLE
Low performance - working slow, after zoom

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-react#62]
Demo: https://codesandbox.io/s/645j3p688k

Try zooming few times and tooltip will work slower and slower.

Could this be traced or checked if the problem is related to Highcharts or the React wrapper?

**Comment by justduy** [comment]
@ppotaczek I created that demo, most of the additional code is to compute the series and the components to help illustrate graphs like plots etc. But the slow performance seems to happen when the area range is included. 

Here is a basic example:
https://codesandbox.io/s/2z4x9vx2r

**Comment by ppotaczek** [comment]
Hi @justduy,

I have successfully simplified your example: http://jsfiddle.net/BlackLabel/ra7qLp1v/

It turns out that the issue is related with `arearange` series and dash style. I reported this problem on Highcharts repository: https://github.com/highcharts/highcharts/issues/9276

Example with the wrapper: https://codesandbox.io/s/rjz3648r2p

Best regards!
