### ISSUE TITLE
Gantt chart throws error after any rerender (version 1.4.0)

### ISSUE THREAD

**Issue by danielbartsch** [highcharts/highcharts-react#63]
This also happens in version 1.5.2 with react 16.

I have reproduced the issue in this repo: https://github.com/danielbartsch/highcharts-react-official-bug-reproduce

Whenever the chart rerenders, there's an error:
```
Uncaught TypeError: Cannot set property 'index' of undefined
```
Then nothing works anymore, and the yAxis disappears.

**Comment by ppotaczek** [comment]
Hi @danielbartsch,

Thank you for reporting this problem. This issue is not related with the wrapper, but with Highcharts.
I reproduced this problem without 'highcharts-react' wrapper: https://jsfiddle.net/BlackLabel/8sxraqdp/ 
and I reported it on Highcharts repository: https://github.com/highcharts/highcharts/issues/9269

**Comment by danielbartsch** [comment]
Oh, thanks for reproducing it without the wrapper. So this can be closed.
