### ISSUE TITLE
Bubble chart with NextJS and highcharts-more

### ISSUE THREAD

**Issue by aorsten** [highcharts/highcharts-react#76]
Probably related to: https://github.com/highcharts/highcharts-react/issues/16 (it didn't solve it for me)

I am making an app with NextJS, which is mostly React. I have been using many different chart items with success, like line/spline/area/scatter/column, etc. Now I needed to add bubble charts, and thus it seems I need highcharts-more.

I tried applying HighchartsMore like this:

```
import Highcharts from 'highcharts'
import HC_More from 'highcharts/highcharts-more'
import HighchartsReact from 'highcharts-react-official'

HC_More(Highcharts)
```

and I have not changed the code for charts in the render method since it worked for all the other chart types:
```
class BaseChart extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <figure className="figure w-100">
                <HighchartsReact 
                    highcharts={Highcharts}
                    options={this.props.options}
                />
                <style jsx>{`
                    figure {
                        margin-top: 3em;
                        margin-bottom: 3em;
                    }
                `}</style>
            </figure>
        );
    }
}
```

Without the HC_More lines, I get error #17, since 'bubble' charts don't exist. However, with the lines, I get:
```
Uncaught (in promise) Error: n is not a function
    at C:\(...)\node_modules\highcharts\highcharts-more.js:8:280
    at C:\(...)\node_modules\highcharts\highcharts-more.js:11:268
    at Module../app/(...)/BaseChart.js
```

I have been struggling with this for many hours, and hope someone knows how to get this working?

**Comment by aorsten** [comment]
I have the exact same experience, @pa87901. Which probably means it could be solved somehow?

**Comment by ppotaczek** [comment]
Hi aorsten, hi pa87901,

Thank you for reporting this issue.

@aorsten, is it possible for you to prepare and send me some minimal project that presents this problem?

@pa87901, do you also use NextJS?

**Comment by pa87901** [comment]
Hi ppotaczek,

No, I am using ReactJS.

**Comment by aorsten** [comment]
@ppotaczek , I have recreated it in a really simple next-js project. It's in the uploaded zip file:
[hcmore.zip](https://github.com/highcharts/highcharts-react/files/2664843/hcmore.zip)

To create it, I suppose this will work:

1. Unpack to a folder you name `hcmore`.
2. do `npm install` inside the folder.
3. do `npm run dev` and open localhost:3000.

Now you should have a working scatter chart. Then:

- To get the error, simply uncomment the HC_More lines, and change the chart type to "bubble", and refresh the page.

- To avoid the error, as @pa87901 also reports, refresh the page with scatter, and the HC_More lines commented out. Then:
1. Uncomment the 2 HC_More lines, and save. (dont refresh the page, but let it update)
2. Change chart type from "scatter" to "bubble" and save (dont refresh the page, but let it update)

Now you should have a working bubble chart. But if you refresh the page, the error returns.

Thanks for having a look at this!

**Comment by KacperMadej** [comment]
Thank you for the demo @aorsten 

Code in `index.js` runs at twice. First run is done in an environment that lacks `window` (server side) and causes Highcharts to be loaded, but not initialized - see first few lines of code: http://code.highcharts.com/6.2.0/highcharts.src.js (it's a link to version 6.2.0 because that version is used in your demo project, but it's not different in current v7.0.0).

Easy fix is to place all modules inits in a `if` checking if `Highcharts` is an object or a function. It should be an object for modules initialization to work without any errors, so code like below is an easy fix:

```js
if (typeof Highcharts === 'object') {
    HC_More(Highcharts)
}
```

After a file save the project is rebuild, but imported libraries are not reloaded. Because of this if you will change Highcharts instance (e.g. through a module initialization) and save the `index.js` file with those changes removed they will stay. The code run on environment without `window` defined runs once, so after `index.js` file saves you are safe - this should explain why saving helped.

The error is not about this repository's React wrapper for Highcharts - it's about loading Highcharts in an environment where it cannot be build because it requires browser environment with `window` and other related features. This is a know issue with NextJS and is covered here: https://github.com/zeit/next.js/wiki/FAQ#i-use-a-library-which-throws-window-is-undefined

**Comment by skoch** [comment]
I had the same issue however mine was with using `highcharts/modules/sankey`.

I know about the whole `window` issue with Next JS so my first move was to upgrade functional Component to a class Component and put the initialization in `componentDidMount` however that created a different error which left me stumped:

![image](https://user-images.githubusercontent.com/112034/50261202-72c7e400-03d9-11e9-8910-3f24cb4ef272.png)

`Uncaught TypeError: t[(e.contructorType || "chart")]`

Anyone have insight as to why attempting to initialize in `componentDidMount` doesn't work?
```javascript
componentDidMount() {
  addSankeyModule(Highcharts);
}
```

Regardless, thanks for the obvious (in hindsight) solution.

**Comment by KacperMadej** [comment]
@skoch 
Just from the look of the error it refers to this code line:
https://github.com/highcharts/highcharts-react/blob/8642adb61a534cc0d24b41d2c6d63e05dd612b6c/src/HighchartsReact.js#L13

Error like that might be caused by:
- lack of Highcharts as a prop and on `window`
- wrong `constructorType` used (could be a typo)
- Highcharts library is not loaded correctly (e.g. at the time of the error it's a function and not an object)

Please try checking the above options and if you could provide a way to recreate the problem then we could help you with debugging.

**Comment by KacperMadej** [comment]
If you would define a custom constructor (like it's done through custom code for [sparkline](https://www.highcharts.com/demo/sparkline)) then the wrapper will work through `constructorType`.

Docs says:

> String for constructor method, defaults to 'chart'. Other official constructors are:
> 
> 'stockChart' for Highstock charts
> 'mapChart' for Highmaps charts

Another official constructor is `ganttChart`. In case of doubt please check live demo of pure JS Highcharts to check what constructor is being used for what chart. However, the general rule is to use constructor defined for a product (Highcharts, Highstock, Highmaps, Highcharts Gantt). As always, in case you have a need for technical support please use https://www.highcharts.com/blog/support/

I hope this info will clear thing up, but please ask if anything still needs to be better explained.

Highcharts will be an object or a function depending on where it is loaded. The Highcharts file starts with:

```js
'use strict';
(function (root, factory) {
	if (typeof module === 'object' && module.exports) {
		module.exports = root.document ?
			factory(root) :
			factory;
	} else if (typeof define === 'function' && define.amd) {
		define(function () {
			return factory(root);
		});
	} else {
		root.Highcharts = factory(root);
	}
}(typeof window !== 'undefined' ? window : this, function (win) {
```

Different ways of loading Highcharts are listed here: https://github.com/highcharts/highcharts#download-and-install-highcharts

**Comment by TillaTheHun0** [comment]
@KacperMadej thanks for that shim suggestion while the issue still exists with NextJS 👍 . I can confirm that works.
